//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApplication.DataLayer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataLayer.IDataProviderService")]
    public interface IDataProviderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyList", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyListResponse")]
        WcfService.Models.OsobaCollection GetOsobyList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyList", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyListResponse")]
        System.Threading.Tasks.Task<WcfService.Models.OsobaCollection> GetOsobyListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/SaveOsobyToXml", ReplyAction="http://tempuri.org/IDataProviderService/SaveOsobyToXmlResponse")]
        void SaveOsobyToXml(WcfService.Models.Osoba[] osoby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/SaveOsobyToXml", ReplyAction="http://tempuri.org/IDataProviderService/SaveOsobyToXmlResponse")]
        System.Threading.Tasks.Task SaveOsobyToXmlAsync(WcfService.Models.Osoba[] osoby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobaByID", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobaByIDResponse")]
        WcfService.Models.Osoba GetOsobaByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobaByID", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobaByIDResponse")]
        System.Threading.Tasks.Task<WcfService.Models.Osoba> GetOsobaByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/AddOsoba", ReplyAction="http://tempuri.org/IDataProviderService/AddOsobaResponse")]
        void AddOsoba(string Meno, string Priezvisko, System.DateTime DatumNarodenia, string Ulica, int Cislo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/AddOsoba", ReplyAction="http://tempuri.org/IDataProviderService/AddOsobaResponse")]
        System.Threading.Tasks.Task AddOsobaAsync(string Meno, string Priezvisko, System.DateTime DatumNarodenia, string Ulica, int Cislo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/DeleteOsobaById", ReplyAction="http://tempuri.org/IDataProviderService/DeleteOsobaByIdResponse")]
        int DeleteOsobaById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/DeleteOsobaById", ReplyAction="http://tempuri.org/IDataProviderService/DeleteOsobaByIdResponse")]
        System.Threading.Tasks.Task<int> DeleteOsobaByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/EditOsoba", ReplyAction="http://tempuri.org/IDataProviderService/EditOsobaResponse")]
        void EditOsoba(int Id, string Meno, string Priezvisko, System.DateTime DatumNarodenia, string Ulica, int Cislo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/EditOsoba", ReplyAction="http://tempuri.org/IDataProviderService/EditOsobaResponse")]
        System.Threading.Tasks.Task EditOsobaAsync(int Id, string Meno, string Priezvisko, System.DateTime DatumNarodenia, string Ulica, int Cislo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyByMeno", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyByMenoResponse")]
        WcfService.Models.Osoba[] GetOsobyByMeno(string c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyByMeno", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyByMenoResponse")]
        System.Threading.Tasks.Task<WcfService.Models.Osoba[]> GetOsobyByMenoAsync(string c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyByPriezvisko", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyByPriezviskoResponse")]
        WcfService.Models.Osoba[] GetOsobyByPriezvisko(string c, WcfService.Models.Osoba[] s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyByPriezvisko", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyByPriezviskoResponse")]
        System.Threading.Tasks.Task<WcfService.Models.Osoba[]> GetOsobyByPriezviskoAsync(string c, WcfService.Models.Osoba[] s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyByDatumNarodenia", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyByDatumNarodeniaResponse")]
        WcfService.Models.Osoba[] GetOsobyByDatumNarodenia(System.DateTime dt, WcfService.Models.Osoba[] s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyByDatumNarodenia", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyByDatumNarodeniaResponse")]
        System.Threading.Tasks.Task<WcfService.Models.Osoba[]> GetOsobyByDatumNarodeniaAsync(System.DateTime dt, WcfService.Models.Osoba[] s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyByUlica", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyByUlicaResponse")]
        WcfService.Models.Osoba[] GetOsobyByUlica(string c, WcfService.Models.Osoba[] s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyByUlica", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyByUlicaResponse")]
        System.Threading.Tasks.Task<WcfService.Models.Osoba[]> GetOsobyByUlicaAsync(string c, WcfService.Models.Osoba[] s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyByCislo", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyByCisloResponse")]
        WcfService.Models.Osoba[] GetOsobyByCislo(int i, WcfService.Models.Osoba[] s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataProviderService/GetOsobyByCislo", ReplyAction="http://tempuri.org/IDataProviderService/GetOsobyByCisloResponse")]
        System.Threading.Tasks.Task<WcfService.Models.Osoba[]> GetOsobyByCisloAsync(int i, WcfService.Models.Osoba[] s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataProviderServiceChannel : MVCApplication.DataLayer.IDataProviderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataProviderServiceClient : System.ServiceModel.ClientBase<MVCApplication.DataLayer.IDataProviderService>, MVCApplication.DataLayer.IDataProviderService {
        
        public DataProviderServiceClient() {
        }
        
        public DataProviderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataProviderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataProviderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataProviderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfService.Models.OsobaCollection GetOsobyList() {
            return base.Channel.GetOsobyList();
        }
        
        public System.Threading.Tasks.Task<WcfService.Models.OsobaCollection> GetOsobyListAsync() {
            return base.Channel.GetOsobyListAsync();
        }
        
        public void SaveOsobyToXml(WcfService.Models.Osoba[] osoby) {
            base.Channel.SaveOsobyToXml(osoby);
        }
        
        public System.Threading.Tasks.Task SaveOsobyToXmlAsync(WcfService.Models.Osoba[] osoby) {
            return base.Channel.SaveOsobyToXmlAsync(osoby);
        }
        
        public WcfService.Models.Osoba GetOsobaByID(int id) {
            return base.Channel.GetOsobaByID(id);
        }
        
        public System.Threading.Tasks.Task<WcfService.Models.Osoba> GetOsobaByIDAsync(int id) {
            return base.Channel.GetOsobaByIDAsync(id);
        }
        
        public void AddOsoba(string Meno, string Priezvisko, System.DateTime DatumNarodenia, string Ulica, int Cislo) {
            base.Channel.AddOsoba(Meno, Priezvisko, DatumNarodenia, Ulica, Cislo);
        }
        
        public System.Threading.Tasks.Task AddOsobaAsync(string Meno, string Priezvisko, System.DateTime DatumNarodenia, string Ulica, int Cislo) {
            return base.Channel.AddOsobaAsync(Meno, Priezvisko, DatumNarodenia, Ulica, Cislo);
        }
        
        public int DeleteOsobaById(int Id) {
            return base.Channel.DeleteOsobaById(Id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteOsobaByIdAsync(int Id) {
            return base.Channel.DeleteOsobaByIdAsync(Id);
        }
        
        public void EditOsoba(int Id, string Meno, string Priezvisko, System.DateTime DatumNarodenia, string Ulica, int Cislo) {
            base.Channel.EditOsoba(Id, Meno, Priezvisko, DatumNarodenia, Ulica, Cislo);
        }
        
        public System.Threading.Tasks.Task EditOsobaAsync(int Id, string Meno, string Priezvisko, System.DateTime DatumNarodenia, string Ulica, int Cislo) {
            return base.Channel.EditOsobaAsync(Id, Meno, Priezvisko, DatumNarodenia, Ulica, Cislo);
        }
        
        public WcfService.Models.Osoba[] GetOsobyByMeno(string c) {
            return base.Channel.GetOsobyByMeno(c);
        }
        
        public System.Threading.Tasks.Task<WcfService.Models.Osoba[]> GetOsobyByMenoAsync(string c) {
            return base.Channel.GetOsobyByMenoAsync(c);
        }
        
        public WcfService.Models.Osoba[] GetOsobyByPriezvisko(string c, WcfService.Models.Osoba[] s) {
            return base.Channel.GetOsobyByPriezvisko(c, s);
        }
        
        public System.Threading.Tasks.Task<WcfService.Models.Osoba[]> GetOsobyByPriezviskoAsync(string c, WcfService.Models.Osoba[] s) {
            return base.Channel.GetOsobyByPriezviskoAsync(c, s);
        }
        
        public WcfService.Models.Osoba[] GetOsobyByDatumNarodenia(System.DateTime dt, WcfService.Models.Osoba[] s) {
            return base.Channel.GetOsobyByDatumNarodenia(dt, s);
        }
        
        public System.Threading.Tasks.Task<WcfService.Models.Osoba[]> GetOsobyByDatumNarodeniaAsync(System.DateTime dt, WcfService.Models.Osoba[] s) {
            return base.Channel.GetOsobyByDatumNarodeniaAsync(dt, s);
        }
        
        public WcfService.Models.Osoba[] GetOsobyByUlica(string c, WcfService.Models.Osoba[] s) {
            return base.Channel.GetOsobyByUlica(c, s);
        }
        
        public System.Threading.Tasks.Task<WcfService.Models.Osoba[]> GetOsobyByUlicaAsync(string c, WcfService.Models.Osoba[] s) {
            return base.Channel.GetOsobyByUlicaAsync(c, s);
        }
        
        public WcfService.Models.Osoba[] GetOsobyByCislo(int i, WcfService.Models.Osoba[] s) {
            return base.Channel.GetOsobyByCislo(i, s);
        }
        
        public System.Threading.Tasks.Task<WcfService.Models.Osoba[]> GetOsobyByCisloAsync(int i, WcfService.Models.Osoba[] s) {
            return base.Channel.GetOsobyByCisloAsync(i, s);
        }
    }
}
